// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/game/result": {
            "post": {
                "description": "register new player and save score or save score in exist player",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Save game result",
                "parameters": [
                    {
                        "description": "Game result with score",
                        "name": "game_result",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ResultRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResultResponse"
                        }
                    }
                }
            }
        },
        "/history": {
            "get": {
                "description": "shows the last 10 games played",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "get games history",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.GetHistoryResponse"
                            }
                        }
                    }
                }
            }
        },
        "/leaderboard": {
            "get": {
                "description": "shows the specified number of leaders",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "get leaderboard",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "leaders count",
                        "name": "top",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.GetLeadersResponse"
                            }
                        }
                    }
                }
            }
        },
        "/player/{name}": {
            "get": {
                "description": "get player profile by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "player"
                ],
                "summary": "show palayer profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Player name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetProfileResponse"
                        }
                    }
                }
            }
        },
        "/stats": {
            "get": {
                "description": "get int",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "show total_game count",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetTotalGameResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.GetHistoryResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "played_at": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                }
            }
        },
        "dto.GetLeadersResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "rank": {
                    "type": "integer"
                },
                "score": {
                    "type": "integer"
                }
            }
        },
        "dto.GetProfileResponse": {
            "type": "object",
            "properties": {
                "best_score": {
                    "type": "integer"
                },
                "games_played": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "rank": {
                    "type": "integer"
                },
                "registered_at": {
                    "type": "string"
                },
                "total_score": {
                    "type": "integer"
                }
            }
        },
        "dto.GetTotalGameResponse": {
            "type": "object",
            "properties": {
                "total_games": {
                    "type": "integer"
                }
            }
        },
        "dto.ResultRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                }
            }
        },
        "dto.ResultResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "new_total_score": {
                    "type": "integer"
                },
                "rank": {
                    "type": "integer"
                }
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/",
	Schemes:          []string{},
	Title:            "Leaderboard API",
	Description:      "This is a project for getting acquainted with Redis.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
